name: Run Cypress on Wednesday

on:
  schedule:
    # Programa para ejecutar cada miércoles a las 14:00 hora española (CET)
    - cron: "0 13 * * 3" # Hora en UTC (14:00 CET corresponde a 13:00 UTC)

jobs:
  run-cypress:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Usa la versión que necesites

      # Step 3: Instala las dependencias
      - name: Install dependencies
        run: npm install

      # Step 4: Ejecuta el test de Cypress
      - name: Run Cypress
        run: npx cypress run --spec "cypress/e2e/wednesday.spec.js"
