name: Run Cypress on Wednesday

on:
  # Permite ejecutar el workflow de forma manual
  workflow_dispatch:

  # Configuración para que se ejecute automáticamente cada miércoles
  schedule:
    - cron: '18 14 * * 3'
    #- cron: "0 * * * *" # Cada hora

jobs:
  run-cypress:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Cambia la versión si es necesario

      # Step 3: Instala las dependencias
      - name: Install dependencies
        run: npm install

      # Step 4: Ejecuta el test de Cypress
      - name: Run Cypress
        run: npx cypress run --spec "cypress/e2e/wednesday.spec.js"
