name: Run Cypress on Wednesday

on:
  # Permite ejecutar el workflow de forma manual
  workflow_dispatch:

  # Configuración para que se ejecute automáticamente cada miércoles a las 00:02
  schedule:
    - cron: "2 23 * * 2"

permissions:
  contents: read

jobs:
  run-cypress:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 3: Instala las dependencias
      - name: Install dependencies
        run: npm install

      # Step 4: Ejecuta el test de Cypress
      - name: Run Cypress
        run: npx cypress run --spec "cypress/e2e/wednesday.spec.js"
